### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by webhive** [AdamYellen/Klicky-Probe-macros#1]
Recently updated macros and now getting the following error

![image](https://github.com/AdamYellen/Klicky-Probe-macros/assets/1154997/46db11d0-54e7-47d9-92f0-76c15b21ed8c)

**Comment by webhive** [comment]
> Recently updated macros and now getting the following error
> 
> ![image](https://user-images.githubusercontent.com/1154997/243759190-46db11d0-54e7-47d9-92f0-76c15b21ed8c.png)

PS: Updated to latest commit `24197b4beb34ffdaa5018d50f350b6240e2a0e53`

**Comment by AdamYellen** [comment]
Hi @webhive,

My project simply syncs with the upstream project. I don't modify any files so I have to assume that any syntax errors existed upstream. Has this issue since been resolved?
