### ISSUE TITLE
sync-push action needs to be re-enabled

### ISSUE THREAD

**Issue by nkean** [AdamYellen/Klicky-Probe-macros#2]
@AdamYellen Looks like GitHub has automatically disabled the sync-push action due to inactivity. Recent updates to klicky-probe macros aren't currently being reflected here and recent changes to Klipper have forced necessary updates to the macros.

**Comment by AdamYellen** [comment]
Sorry about that! The notice got lost in spam. I reenabled the workflow and manually did a build.

**Comment by nkean** [comment]
Thanks for the quick response!
